site_name: dateint
site_url: https://amaralbf.github.io/dateint/
repo_url: https://github.com/amaralbf/dateint
repo_name: amaralbf/dateint
site_author: Bruno Amaral

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  icon:
    logo: material/calendar-month

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - API: api.md
  - Release Notes: release_notes.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            show_root_toc_entry: false
            show_source: false
            show_root_heading: true

extra_css:
  - css/style.css
